---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: sample-producer-job
  name: sample-producer-job
spec:
  completions: 1
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: sample-producer-job
    spec:
      restartPolicy: OnFailure
      activeDeadlineSeconds: 300
      containers:
      - name: sample-producer
        image: strimzi/hello-world-producer:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: demo-cluster-kafka-bootstrap:9092
          - name: TOPIC
            value: greetings
          - name: DELAY_MS
            value: "750"
          - name: LOG_LEVEL
            value: "INFO"
          - name: MESSAGE_COUNT
            value: "999"
